# -*- mode: dockerfile; coding: utf-8 -*-
FROM debian:buster AS build
RUN apt-get update && apt-get -y --no-install-recommends install \
       guile-2.2 \
  && rm -rf /var/lib/apt/lists/*

COPY scheme-script /usr/bin/
